#! /bin/sh

### BEGIN INIT INFO
# Provides:          ocpdaemon
# Required-Start:    $all
# Required-Stop:     $all
# Default-Satart:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the open cell outbound server
# Description:       starts open cell using start-stop-daemon
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON="/usr/bin/ruby /var/www/ocp/current/tasks/outbound.rb"
NAME=outbound
DESC=outbound
PIDFILE=/var/www/ocp/current/log/outbound.pid

#test -x $DAEMON || exit 0
#because of the required full path to ruby cannot do the above test command

set -e

. /lib/lsb/init-functions

case "$1" in
  start)
    echo -n "Starting $DESC: "
    start-stop-daemon --start --background --make-pidfile --quiet --pidfile $PIDFILE \
        --exec $DAEMON -- $DAEMON_OPTS || true
    echo "$NAME."
    ;;
  stop)
    echo -n "Stopping $DESC: "
    start-stop-daemon --stop --verbose --pidfile $PIDFILE \
        --exec $DAEMON || true
    echo "$NAME."
    ;;
  restart|force-reload)
    echo -n "Restarting $DESC: "
    start-stop-daemon --stop --quiet --pidfile \
        $PIDFILE --exec $DAEMON || true
    sleep 1
    start-stop-daemon --start --background --make-pidfile --quiet --pidfile \
        $PIDFILE --exec $DAEMON -- $DAEMON_OPTS || true
    echo "$NAME."
    ;;
  status)
      status_of_proc -p $PIDFILE "$DAEMON" opencell && exit 0 || exit $?
      ;;
  *)
    N=/etc/init.d/$NAME
    echo "Usage: $N {start|stop|restart|reload|force-reload|status}" >&2
    exit 1
    ;;
esac

exit 0
